version: "3.8"
services:
  postgres:
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: luis.diaz@sinco.co
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
